name: Pull Request Build and Deploy

on:
  pull_request:
    branches:
      - develop
    paths-ignore:
      - '.github/workflows/**'
      - '**.md'

env:
  PR_REPO_NAME: app-pr-${{ github.event.pull_request.node_id }}

jobs:
  create-page-host:
    runs-on: ubuntu-latest
    steps:
      - name: Create new repository for temporary deployment
        uses: mktcode/create-repository-action@v1
        with:
          name: ${{ env.PR_REPO_NAME }}
          org: ${{ env.GITHUB_REPOSITORY_OWNER }}
          access-token: ${{ secrets.PAT }}

  pr-build-deploy:
    needs: create-page-host
    runs-on: ubuntu-latest
    environment:
      name: pr-staging
      url: https://${{ env.GITHUB_REPOSITORY_OWNER }}.github.io/${{ env.PR_REPO_NAME }}

    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: 16
          cache: 'yarn'

      - run: yarn install --frozen-lockfile
      - run: yarn build
        env:
          CI: false

      - name: deploy to gh-pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          deploy_key: ${{ secrets.PAT }}
          external_repository: ${{ env.GITHUB_REPOSITORY_OWNER }}/${{ env.PR_REPO_NAME }}
          publish_dir: ./build
